# Generated by Django 5.1.2 on 2024-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='department',
            name='number_of_employees',
            field=models.CharField(default=400, max_length=40),
        ),
    ]
